export const SET_COURSES = 'COURSES/SET_COURSES';
export const SET_SUBJECTS = 'COURSES/SET_SUBJECTS';
export const SET_GENRES = 'COURSES/SET_GENRES';
export const SET_GRADES = 'COURSES/SET_GRADES';
export const SET_FILTER_PARAMS = 'FILTER/SET_FILTER_PARAMS';
export const SET_SEARCH_PHRASE = 'SEARCH/SET_SEARCH_PHRASE';
export const SET_ACTIVE_UNIT = 'APP/SET_ACTIVE_UNIT';
export const SET_APP_IS_READY = 'APP/SET_APP_IS_READY';
